# Generated by Django 3.0.8 on 2020-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20200821_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imgprincipal',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/static/servicios/images', verbose_name='Principal'),
        ),
    ]
