# Generated by Django 3.0.8 on 2020-08-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20200821_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imgprincipal',
            field=models.ImageField(default='servicios/static/servicios/images/no-img.jpg', upload_to='galeria', verbose_name='Principal'),
        ),
    ]
