# Generated by Django 3.0.8 on 2020-08-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20200821_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesprincipales',
            name='servicio',
        ),
    ]
